### ISSUE TITLE
"not a valid symbol name" when using strings as map keys that are not valid symbol identifiers

### ISSUE THREAD

**Issue by nrpeterson** [opendatagroup/hadrian#11] opened 2016-06-15 20:57 UTC
Everything I've read in the PFA documentation says that the keys in maps can be ANY strings.  However,  consider the following expression:

```json
        {
          "new" : {
            "1st_4th" : 14.0,
            "10th" : 7.0,
            "Some_college" : 1.0,
            "HS_grad" : 0.0,
            "Preschool" : 15.0,
            "9th" : 10.0,
            "Assoc_acdm" : 6.0,
            "5th_6th" : 13.0,
            "7th_8th" : 8.0,
            "11th" : 5.0,
            "Masters" : 3.0,
            "12th" : 11.0,
            "Doctorate" : 12.0,
            "Prof_school" : 9.0,
            "Bachelors" : 2.0,
            "Assoc_voc" : 4.0
          },
          "type" : {
            "type" : "map",
            "values" : "double"
          }
        }
```

Hadrian is choking on this, saying that:
```
"1st_4th" is not a valid symbol name
```

**Comment by nrpeterson** [comment] 2016-06-15 20:58
I should point out that Titus considers this completely valid.

**Comment by collinbennett** [comment] 2016-06-16 01:17
I believe map keys have to be valid symbols and the regex for that is 
  `[A-Za-z_][A-Za-z0-9_]*`

I'll check this and look into why you are seeing different behavior between Titus and Hadrian

**Comment by jpivarski** [comment] 2016-06-16 01:23
Maps are supposed to be like Python dictionaries: the key names should be unrestricted. I'll take a look.

**Comment by jpivarski** [comment] 2016-06-16 01:56
Page 52 of the spec (https://github.com/datamininggroup/pfa/raw/master/pfa-specification.pdf) covers this special form and says nothing about constraints on the map keys. (It also doesn't mention constraints on the record fields, but if they weren't valid field names, the Avro type definition for that record would fail.)

JSON objects whose values are expressions are read in on line 667 of reader.scala (https://github.com/opendatagroup/hadrian/blob/master/hadrian/src/main/scala/com/opendatagroup/hadrian/reader.scala#L667) in `readExpressionMap`. The corresponding line 508 of reader.py in Titus (https://github.com/opendatagroup/hadrian/blob/master/titus/titus/reader.py#L507) has no such constraint. This part of the two codebases are supposed to mirror each other as much as Scala and Python can.

It looks like the `validSymbolName` constraint was put into Hadrian because `readExpressionMap` can be used to read in variable declarations in "let" special forms (and a few other, similar things: defining variables in "for" loops, for instance). The necessary check for these cases might be applied both here (reader.scala) and in the AST (ast.scala).

reader.scala (and reader.py) is too early to apply the `validSymbolName` constraint: at that point in the code, we see JSON structures, but we don't know the PFA context yet (whether it's a "let" form or a "new" form or what). It should be applied in ast.scala (and pfaast.py), where `Let` and `NewObject` are different classes. The `validSymbolName` check should be applied in the `walk` method as a PFASemanticException, rather than a PFASyntaxExpression.

**Comment by nrpeterson** [comment] 2016-06-16 17:25
Thanks @jpivarski and @collinbennett .  I haven't looked at the source; but, if this is a relatively straight-forward fix, I'd happily put something together and submit a pull request for it.  If you'd like me to start digging into it, just let me know.  I should be able to put something together next week.

**Comment by jpivarski** [comment] 2016-06-16 17:53
That would be helpful, thanks!

We'd need to be careful, though, because this part of the code would affect many different scoring engines in different ways: we'd want to be sure that every special form that uses readExpressionMap rejects invalid symbol names if it's supposed to. They should do so as PFASyntaxErrors in the constructor of the corresponding Ast subclass. (I'm refining what I said before about validSymbolName being a semantic error; you can determine it locally as long as you know what kind of special form you're in. This is more like the PFASyntaxErrors you see in the Ast subclass constructors than anything else.)

The Ast subclasses that are read in through readExpressionMap are:

   * [Let](https://github.com/opendatagroup/hadrian/blob/master/hadrian/src/main/scala/com/opendatagroup/hadrian/ast.scala#L2395) should check validSymbolName because it declares variables.
   * [SetVar](https://github.com/opendatagroup/hadrian/blob/master/hadrian/src/main/scala/com/opendatagroup/hadrian/ast.scala#L2476) should also because it reassigns variables.
   * [For](https://github.com/opendatagroup/hadrian/blob/master/hadrian/src/main/scala/com/opendatagroup/hadrian/ast.scala#L3441) has two nodes that go through readExpressionMap: `init` and `step`, which declare and reassign variables, respectively.
   * [IfNotNull](https://github.com/opendatagroup/hadrian/blob/master/hadrian/src/main/scala/com/opendatagroup/hadrian/ast.scala#L3983) declares variables in `exprs`.
   * [NewObject](https://github.com/opendatagroup/hadrian/blob/master/hadrian/src/main/scala/com/opendatagroup/hadrian/ast.scala#L2178) handles new maps and new records. The new maps should _not_ check validSymbolName (as you pointed out), and the new records doesn't need to because that's already checked by the Avro type declaration. In principle, valid record field names could be different from valid symbol names (in practice, it's not). You could simply leave this one alone.
   * [Pack](https://github.com/opendatagroup/hadrian/blob/master/hadrian/src/main/scala/com/opendatagroup/hadrian/ast.scala#L4235) goes through readExpressionMap (through readStringExpressionPairs), but it doesn't have anything to do with declaring or reassigning symbols.
   * [Unpack](https://github.com/opendatagroup/hadrian/blob/master/hadrian/src/main/scala/com/opendatagroup/hadrian/ast.scala#L4307) I don't see evidence that Unpack goes through readExpressionMap, but its `format` declares variables and I thought it would have used something like readExpressionMap to do it.

That's an exhaustive list; I checked it by walking through the closure of readExpressionMap up to readArgument, where forms are created as Ast instances. Make sure that these forms still work (refusing bad variable names and accepting anything when not declaring variables). Also, this only affects Hadrian.

Perhaps we should start asking for a small unit test with each pull request, probably with the same name?

**Comment by nrpeterson** [comment] 2016-06-16 23:59
I can definitely manage some unit tests; no worries there. :-)  I'm moving this weekend, so I won't be able to start looking at this til next week; but, I'll get familiar with the source, and let you know how it goes.

**Comment by nrpeterson** [comment] 2016-06-30 22:29
Hey folks,

Sorry for the slow movement on this (moving is more of a pain than I remembered... even though it hasn't been that long).

I've got a bunch of tests in place, and I've got them all showing green.  But, there are two questions to address:

1. Do you really want the input validation done twice in the case of reading in from JSON -- that is, once in `readExpressionMap` and once in the constructors themselves?  Or, will just doing it in the AST constructors that require it be sufficient?  I can submit either way.

2. I'm getting some failing tests that seem to be unrelated, from the ThreadSafetySuite.  Two of them seem to be due to missing fields, such as:
```
com.opendatagroup.hadrian.errors.PFASyntaxException: PFA syntax error at YAML lines 2 to 12: folding engines must include "zero" and "merge" top-level fields
```
The third is in the "Thread safety must allow an action and a function from different engines to run at the same time" test:
```
from the "Thread safety must not run two fold actions at the same time" test.  The other test is "Thread safety must allow two fold actions from different engines to run at the same time", and it is identical.

org.scalatest.exceptions.TestFailedException: List("start", "fcnstart", "fcnstop", "stop") was not equal to List("start", "fcnstart", "stop", "fcnstop")
```
I just want to make very sure: these aren't my doing, correct?  As in, these failures should not concern me where my commit is concerned?

Thanks!

**Comment by nrpeterson** [comment] 2016-06-30 23:07
For reference, you can see what I changed at https://github.com/nrpeterson/hadrian/commit/9603b73a8a7e044bf72b04669aa2505c56cdb212

**Comment by jpivarski** [comment] 2016-07-01 00:18
The ThreadSafety suite has been off for some time because it's unreliable. It's based on a race condition to test the behavior of concurrent engines, but, naturally, they don't always run when they're supposed to. It's been off for so long that it might be behind in development. "Fold" engines requiring a "merge" element is a new thing. It's not caused by anything you did.

**Comment by nrpeterson** [comment] 2016-07-01 04:46
Alright, awesome.  I'll submit my PR then.  Thanks!

**Comment by collinbennett** [comment] 2016-08-09 12:38
Fixed in branch.  Will be in the release following 0.8.4.

**Closed by collinbennett** 2016-08-09 12:38 UTC
